# Generated by Django 5.0 on 2023-12-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_purchase_data_receipt_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
